### PR TITLE
MDL-66979: Switch to php-webdriver/webdriver

### PR DESCRIPTION
**Pull request by andrewnicols**
To facilitate this we use the oleg-andreyev/MinkPhpWebDriver Mink Driver
rather than any provided by the minkphp project, which have yet to add
support for php-webdrier.

The oleg-andreyev driver is largely complete, but there are a handful of
bugs waiting to be merged. As a result, this branch currently follows my
fork of the driver which is a branch with all of the pull requests
applied. These pull requests are:

oleg-andreyev/MinkPhpWebDriver#8
Opening, closing, and re-opening a window with the same name attempts
to reopen the closed window.
oleg-andreyev/MinkPhpWebDriver#10
Work around a bug in geckodriver whereby the pointer location is not
updated when calling click()
oleg-andreyev/MinkPhpWebDriver#11
Trigger a synthetic change event rather than pressing TAB after
sendKeys.
oleg-andreyev/MinkPhpWebDriver#12
Work around a bug in geckodriver where an ElementNotInteractable error
is thrown when attempting to click on a link whose first child is a
block-level element.
This change moves away from the MoodleSeleium2 Driver and Factory in
favour of the more generic WebDriver and WebDriverFactory.

The changes here also remove the need for the modified syn.js library,
which is no longer used in favour of a true synthetic event.

The customistations in NodeElement are also no longer required as most
of them have been addressed in the php-webdriver/webdriver project, or
are worked around in the oleg-andreyev/MinkPhpWebDriver driver.

### CODE REVIEW

**Comment by stronk7** [comment]
Hi Andrew,

I completely trust the changes above and that they will, together with [MDL-66979](https://tracker.moodle.org/browse/MDL-66979) bring us the much desired w3c webdriver support yay!

Just have 2-3 points to comment about:

1. While pulling changes locally, I've seen a new `w3c` branch coming from this repo. Maybe it was pushed by mistake or is it anything needed for easy testing or so?
2. The 3 PRs are 100% the same, correct?
3. Once merged, we have to tag them: `v3.39.4`, `v3.310.1`, `v3.311.1` and `v3.400.1` are the following release/tag numbers. Do we need to consider changing anything in the versioning schema or is it ok to just make them to continue normally?

Ciao :-)

**Comment by andrewnicols** [comment]
Thanks Eloy,

1) That was my WIP branch. I'll delete it shortly. I need to bump these branches as some of my merge requests have landed.
2) Yup
3) I'm not really sure. Is there any benefit to bumping them in some other way do you think?

**Comment by stronk7** [comment]
> Is there any benefit to bumping them in some other way do you think?

Not really, just in case we want to make it clear when the "switch" to w3c was done. Surely not needed for anything else, so going to proceed with regular (next) tags and done.

Thanks!

**Comment by stronk7** [comment]
Merged and both [v3.311.1](https://packagist.org/packages/moodlehq/behat-extension#v3.311.1) and [v3.400.1](https://packagist.org/packages/moodlehq/behat-extension#v3.400.1) created and available.

Thanks!

**Pull request merged**
