### PR TITLE
Failed Steps should always cause a failure

### PR DESCRIPTION
**Pull request by andrewnicols**
Some types of failed step were ignored and not detected as having either
an Exception, or a Failure result, leading to a false pass result for
that step.

To give a specific example, FailedStepSearchResult is returned when a
Step cannot be found, or when multiple steps match the same search
string.

The FailedStepSearchResult is a StepResult, which does have an exception
and whose `isPassed` method returns false (to indicate a failure),
however the class is not an ExecutedStepResult, and it not an
UndefinedStepResult, or a SkippedStepResult. As a result it is believed
to not support Chained Steps at all, and the result is entirely replace
with a new Exception Test step thereby causing the step to be marked,
incorrectly, as Passed.

This patch adjusts the checking to explicitly check for the presence of:
- any exception; or
- any test failure.

The StepTester should always return a StepResult, which is a type of
TestResult.

Any TestResult which _can_ have any exception _must_ implement the
ExceptionResult interface, and will return a true for the `hasException`
call.

Any TestResult which _can_ have a result _must_ implement the StepResult
Interface, and _must_ return a boolean value for the `isPassed` call.

Using this we can therefore check whether any Step which can either
throw an exception, or be marked as failed, is already in a failure
state and stop testing immediately.

Other TestResult types then fit into two categories:
- those which do not contain any Chained Step; and
- those which make use of the deprecated Chained Step.

For those TestResult instances which _do not_ support chaining, a new step is
performed to check for Exceptions, and only the result of that one test
is returned.

For those TestResult instances which _do_ support chaining, all child
steps are executed.

### CODE REVIEW

**Comment by andrewnicols** [comment]
I will also note that I think it's about time that we moved the exception checking to an AfterStep Hook if at all possible.

**Comment by stronk7** [comment]
Q: To which branches of the extension should we apply this? Is there any core-dependency?

There are a few steps to follow:
- Step 1: We need [MDL-69146](https://tracker.moodle.org/browse/MDL-69146) integrated (point core to current extension releases). It's sort of "locking" any other tagging.
- Step 2 (this PR): Is merged and spread/picked to the target branches. And all them are tagged.
- Step 3: A new MDL is provided, similar to the Step 1, bumping to the new tags all the target branches.

I'm happy to proceed with all the preparation (but the MDL integrations) as far as I know the target versions for this (hence, the initial question).

Ciao :-)

**Comment by andrewnicols** [comment]
A: All of the supported.

I was waiting for an initial PR before progressing with steps 2, and 3.

**Comment by andrewnicols** [comment]
Fixed in core after the migration.

**Pull request closed without merging**
